[versions]
junit = "5.13.4"
kotlin = "1.9.25"
kotlinLogging = "6.0.9"
kotlinter = "3.15.0"
kover = "0.9.2"
mockk = "1.14.2"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api"}
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlinLogging" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }

[bundles]
junit_runtime = [ "junit-platform-launcher", "junit-jupiter-engine" ]
junit_jupiter = [ "junit-jupiter", "junit-jupiter-api" ]